name: Run Selenium Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Every day at 6:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the JUnit project
      - name: Checkout JUnit repo
        uses: actions/checkout@v4

      # Checkout the Automation repo
      - name: Checkout Automation repo
        uses: actions/checkout@v4
        with:
          repository: SarathKumarKosanam/RevDocAdminJunit
          token: ${{ secrets.REPO_PAT }}
          path: automation

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Automation dependency into Maven local repo
      - name: Build Automation dependency
        run: |
          cd automation
          mvn install -DskipTests=true

      # Build JUnit project (now dependency will be found)
      - name: Build JUnit
        run: mvn install -DskipTests=true

      # Run Selenium tests
      - name: Run Selenium tests
        run: mvn test -Dbrowser=headless
