name: Run Selenium Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout JUnit repo
      - name: Checkout JUnit repo
        uses: actions/checkout@v4

      # 2. Checkout Automation repo
      - name: Checkout Automation repo
        uses: actions/checkout@v4
        with:
          repository: SarathKumarKosanam/RevDocAdminJunit
          token: ${{ secrets.REPO_PAT }}
          path: automation

      # 3. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Build Automation
      - name: Build Automation dependency
        run: |
          cd automation
          mvn install -DskipTests=true

      # 5. Build JUnit project
      - name: Build JUnit
        run: mvn install -DskipTests=true

      # 6. Run tests
      - name: Run Selenium tests
        run: mvn test -Dbrowser=headless
