name: Run Selenium Tests

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6:00 UTC
  workflow_dispatch:     # Manual trigger
  push:                  # Run on every push to main
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout automation repo (dependency)
        uses: actions/checkout@v4
        with:
          repository: SarathKumarKosanam/RevDocAdminJunit
          token: ${{ secrets.REPO_PAT }}
          path: automation

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      # Install automation repo into local Maven cache so JUnit project can use it
      - name: Install automation repo locally
        run: |
          cd automation
          mvn clean install -DskipTests=true
          cd ..

      - name: Install dependencies for JUnit project
        run: mvn install -DskipTests=true

      - name: Run Selenium tests
        run: mvn test -Dbrowser=headless
