name: RevDocAdminJUnit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven & Run Tests
        run: mvn clean test

      - name: List target folder (debugging)
        run: ls -R target || true

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports/**

      - name: Upload Extent Reports
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: target/ExtentReports/**

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: target/screenshots/**
