name: Run Selenium Tests

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout this repo (JUnit project)
      - name: Checkout JUnit repo
        uses: actions/checkout@v4

      # 2. Checkout automation repo (dependency)
      - name: Checkout Automation repo
        uses: actions/checkout@v4
        with:
          repository: SarathKumarKosanam/RevDocAdminJunit
          token: ${{ secrets.REPO_PAT }}
          path: automation

      # 3. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Set up Chrome
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      # 5. Build automation project first
      - name: Build Automation dependency
        run: |
          cd automation
          mvn install -DskipTests=true

      # 6. Build JUnit project
      - name: Build JUnit project
        run: mvn install -DskipTests=true

      # 7. Run Selenium tests
      - name: Run Selenium tests
        run: mvn test -Dbrowser=headless
