name: RevDocAdminJUnit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.failure.ignore=true

      - name: Run Tests with Maven
        run: mvn test

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: RevDocAdminJUnit/target/cucumber-reports/**

      - name: Upload Extent Reports
        uses: actions/upload-artifact@v3
        with:
          name: extent-reports
          path: RevDocAdminJUnit/target/ExtentReports/**

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: RevDocAdminJUnit/target/screenshots/**
