name: Run RevDoc Admin JUnit5 Tests

# Triggers
on:
  workflow_dispatch:  # manual trigger
  schedule:          # daily run at 6 AM UTC
    - cron: "0 6 * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build and run tests
      - name: Build & run tests
        run: mvn clean test

      # 5. Upload test reports and screenshots
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/cucumber-reports
            target/ExtentReports
            target/screenshots
