name: Run Selenium Tests (build dependency)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout automation repo (dependency)
        uses: actions/checkout@v4
        with:
          repository: SarathKumarKosanam/RevDocAdminAutomation   # <-- change to correct owner/name
          token: ${{ secrets.REPO_PAT }}                        # required if repo is private
          path: automation

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Build automation project (install to local .m2)
        run: mvn -B -f automation/pom.xml clean install -DskipTests=true

      - name: Build main project & run tests
        run: |
		
          mvn -B -f pom.xml clean test -Dbrowser=headless
		  - name: Checkout automation repo (dependency)
		    uses: actions/checkout@v4
		    with:
		      repository: <OWNER>/<RevDocAdminAutomation>
		      token: ${{ secrets.REPO_PAT }}   # must match the secret name
		      path: automation
