name: Run Selenium-Cucumber-JUnit Tests

on:
  push:
    branches:
      - main      # runs when you push to main
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 2 * * *' # runs daily at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # your Java version

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Edge
        uses: browser-actions/setup-edge@v1

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & run tests
        run: mvn clean test
