# File: .github/workflows/run-tests.yml
name: Run RevDoc Admin JUnit Tests

# Trigger: manual and daily
on:
  workflow_dispatch:       # allows manual trigger
  schedule:
    - cron: "0 1 * * *"   # daily at 01:00 UTC (adjust if needed)

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build project
      - name: Build with Maven
        run: mvn clean install -B

      # 5. Run tests
      - name: Run tests
        run: mvn test -B

      # 6. Upload reports as artifacts
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/cucumber-reports
            target/ExtentReports
