name: RevDocAdminJUnit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: RevDocAdminJunit/target/cucumber-reports/

      - name: Upload Extent Reports
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: RevDocAdminJunit/target/ExtentReports/

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: RevDocAdminJunit/target/screenshots/
